import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rick & Morthy Image Feed',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex w-full min-h-screen flex-col p-24 gap-4">
          <h1 className="text-center text-xl">Rick and Morty Characters</h1>
          {children}
        </main>
      </body>
    </html>
  )
}
